package com.netpulse.whatif.state;

public enum ScenarioType {
    NODE_FAILURE,
    NODE_RECOVERY,
    TRAFFIC_INCREASE,
    TRAFFIC_DECREASE,
    CPU_SPIKE,
    MEMORY_SPIKE,
    LATENCY_INCREASE,
    PACKET_LOSS_INCREASE,
    NETWORK_PARTITION,
    LINK_FAILURE,
    ROUTING_STRATEGY_CHANGE,
    CPU_SCHEDULER_CHANGE,
    COMBINED_SCENARIO
}
