package com.netpulse.whatif.state;

public enum SimulationEventType {
    SNAPSHOT_CAPTURED,
    NODE_FAILED,
    NODE_RECOVERED,
    LINK_FAILED,
    TRAFFIC_CHANGED,
    CPU_CHANGED,
    MEMORY_CHANGED,
    LATENCY_CHANGED,
    PACKET_LOSS_CHANGED,
    HEALTH_CHANGED,
    ROUTE_CHANGED,
    FAILOVER_TRIGGERED,
    TRAFFIC_REROUTED,
    PROCESS_DISPATCHED,
    PROCESS_PREEMPTED,
    PROCESS_COMPLETED,
    SCHEDULER_CHANGED,
    SIMULATION_COMPLETED
}
