package com.netpulse.scheduler.state;

public enum ContextSwitchReason {
    TIME_QUANTUM_EXPIRED,
    HIGHER_PRIORITY,
    PREEMPTION_HIGHER_PRIORITY,
    SHORTER_REMAINING_TIME,
    PREEMPTION_SHORTER_BURST,
    CFS_GRANULARITY_EXCEEDED,
    PROCESS_DISPATCHED,
    PROCESS_BLOCKED,
    IO_REQUEST,
    IO_COMPLETION,
    PROCESS_COMPLETED,
    PROCESS_TERMINATED,
    CPU_REBALANCING,
    NODE_REBALANCING,
    MANUAL
}
